import { SuperBaseCompleteSchema } from "../complete/schema";
import { CLAIMS_REGISTER_DISCLAIMER } from "../superbase/schema";

// Editorial basis: verified footage notes and Claims Register in MaintainPavements.
// Source IDs deliberately remain attached to every shot for coverage audits.
// V04 is a second encode of V03C, not cure footage; use a distinct rolling window.
export const superBaseCompleteJob = SuperBaseCompleteSchema.parse({
  jobId: "superbase-complete-process",
  brandName: "Maintain Pavements",
  productName: "SuperBase",
  contact: { name: "Jon Pepper", phone: "0414 530 836", email: "jon@maintain.com.au", website: "maintain.com.au" },
  disclaimer: CLAIMS_REGISTER_DISCLAIMER,
  music: { src: "audio/superbase-bed.wav", volume: 0.7 },
  realFootageVolume: 0.07,
  requiredSourceIds: ["V01", "V02A", "V02B", "V03A", "V03B", "V03C", "V04", "S04A", "S04B", "AI-GRADE"],
  shots: [
    { id: "opening-problem", sourceId: "AI-BEFORE", kind: "opening", durationSeconds: 3,
      setup: "Stop patching\nthe yard.", payoff: "Bind it.", caption: "Illustrative yard · not a project before-shot",
      media: { src: "ai/before-yard.mp4", kind: "video", ai: true } },
    { id: "intro-preparation", sourceId: "AI-PREPARE", kind: "intro", durationSeconds: 1,
      setup: "A third", payoff: "option.", body: "Between patching and a concrete slab.", caption: "The SuperBase method · five steps",
      media: { src: "ai/prepare-atmosphere.mp4", kind: "video", ai: true } },
    { id: "intro-dose", sourceId: "AI-DOSE", kind: "intro", durationSeconds: 1, entranceOffsetFrames: 30,
      setup: "A third", payoff: "option.", body: "Between patching and a concrete slab.", caption: "The SuperBase method · five steps",
      media: { src: "ai/dose-atmosphere.mp4", kind: "video", ai: true } },
    { id: "intro-compaction", sourceId: "AI-ROLL", kind: "intro", durationSeconds: 1, entranceOffsetFrames: 60,
      setup: "A third", payoff: "option.", body: "Between patching and a concrete slab.", caption: "The SuperBase method · five steps",
      media: { src: "ai/roll-atmosphere.mp4", kind: "video", ai: true } },
    { id: "prepare-V01", sourceId: "V01", kind: "process", durationSeconds: 5.5, step: 1,
      setup: "Prepare", payoff: "the base.", body: "Clear loose material.\nScarify the existing base.", caption: "Recorded preparation · scarifying not filmed",
      media: { src: "footage/V01.mp4", kind: "video", ai: false, startSeconds: 0, position: "50% 48%" } },
    { id: "dose-V02A", sourceId: "V02A", kind: "process", durationSeconds: 5, step: 2,
      setup: "Dose", payoff: "and mix.", body: "Dose to suit your base.\nMix through the full layer.", caption: "Water application · liquid contents unconfirmed",
      media: { src: "footage/V02A.mp4", kind: "video", ai: false, startSeconds: 18.5, framing: "landscape-master" } },
    { id: "grade-photo-illustration", sourceId: "AI-GRADE", kind: "process", durationSeconds: 8, step: 3,
      setup: "Grade", payoff: "to level.", body: "Trim to design level and crossfall\nwhile the base is workable.", caption: "Based on the supplied photo · process illustration",
      media: { src: "ai/grade-levelling.mp4", kind: "video", ai: true } },
    { id: "wet-roll-V02B", sourceId: "V02B", kind: "process", durationSeconds: 3.5, step: 4,
      setup: "Roll", payoff: "and compact.", body: "Wet rolling to final compaction.\nConfirm density against the design.", caption: "Recorded site footage · wet rolling",
      media: { src: "footage/V02B.mp4", kind: "video", ai: false, startSeconds: 0, framing: "landscape-master" } },
    { id: "roll-V03A", sourceId: "V03A", kind: "process", durationSeconds: 4, step: 4, entranceOffsetFrames: 105,
      setup: "Roll", payoff: "and compact.", body: "Wet rolling to final compaction.\nConfirm density against the design.", caption: "Recorded site footage · compaction",
      media: { src: "footage/V03A.mp4", kind: "video", ai: false, startSeconds: 5 } },
    { id: "roll-V03B", sourceId: "V03B", kind: "process", durationSeconds: 3.5, step: 4, entranceOffsetFrames: 225,
      setup: "Roll", payoff: "and compact.", body: "Wet rolling to final compaction.\nConfirm density against the design.", caption: "Recorded site footage · compaction",
      media: { src: "footage/V03B.mp4", kind: "video", ai: false, startSeconds: 5.5 } },
    { id: "roll-V03C", sourceId: "V03C", kind: "process", durationSeconds: 3, step: 4, entranceOffsetFrames: 330,
      setup: "Roll", payoff: "and compact.", body: "Wet rolling to final compaction.\nConfirm density against the design.", caption: "Recorded site footage · compaction",
      media: { src: "footage/V03C.mp4", kind: "video", ai: false, startSeconds: 0 } },
    { id: "roll-V04", sourceId: "V04", kind: "process", durationSeconds: 3, step: 4, entranceOffsetFrames: 420,
      setup: "Roll", payoff: "and compact.", body: "Wet rolling to final compaction.\nConfirm density against the design.", caption: "Recorded site footage · final rolling pass",
      media: { src: "footage/V04.mp4", kind: "video", ai: false, startSeconds: 14.5 } },
    { id: "cure-S04B", sourceId: "S04B", kind: "process", durationSeconds: 4, step: 5,
      setup: "Cure. Then", payoff: "return to service.", body: "Allow the surface to cure.\nReturn-to-service timing varies by site.", caption: "Recorded site surface · cure timing unconfirmed",
      media: { src: "footage/S04B.jpeg", kind: "image", ai: false, framing: "photo" } },
    { id: "surface-S04A", sourceId: "S04A", kind: "process", durationSeconds: 4, step: 5, entranceOffsetFrames: 120,
      setup: "Cure. Then", payoff: "return to service.", body: "Allow the surface to cure.\nReturn-to-service timing varies by site.", caption: "Supplied surface photo · different yard",
      media: { src: "footage/S04A.png", kind: "image", ai: false, framing: "surface-detail", position: "50% 100%" } },
    { id: "testing-method", sourceId: "CLAIMS-C9", kind: "proof", durationSeconds: 4.5,
      setup: "Your material.", payoff: "Your proof.", body: "Laboratory soaked CBR testing,\nbefore treatment and after cure.", caption: "Testing method · no measured result presented" },
    { id: "indicative-cost", sourceId: "CLAIMS-C1", kind: "cost", durationSeconds: 6,
      setup: "60–70%", payoff: "Indicatively below\nengineered concrete\nhardstand.", body: "Indicative. Varies with base material, climate and duty. Confirmed by site trial and testing.", caption: "Unit-rate comparison · engineered concrete hardstand" },
    { id: "contact-and-disclaimer", sourceId: "CLAIMS-END", kind: "end", durationSeconds: 12,
      setup: "Let’s look at", payoff: "your yard.", body: "Start with your material.\nConfirm with a site trial and testing." },
  ],
});
