import {
  CLAIMS_REGISTER_DISCLAIMER,
  SuperBasePromoSchema,
} from "../superbase/schema";

// Editorial source: the verified notes in MaintainPavements/03 Footage.
// AI appears only in the first ten seconds, as explicitly labelled illustration.
// All measured performance, names of sites and elapsed cure claims are omitted.
export const superBaseTestJob = SuperBasePromoSchema.parse({
  jobId: "superbase-test",
  brandName: "Maintain Pavements",
  productName: "SuperBase",
  contact: {
    name: "Jon Pepper",
    phone: "0414 530 836",
    email: "jon@maintain.com.au",
    website: "maintain.com.au",
  },
  disclaimer: CLAIMS_REGISTER_DISCLAIMER,
  realFootageVolume: 0.12,
  shots: [
    {
      id: "00-illustrative-problem",
      kind: "problem",
      durationSeconds: 4,
      media: { src: "ai/before-yard.mp4", kind: "video", ai: true },
      kicker: "The maintenance cycle",
      setup: "Stop patching the yard.",
      payoff: "Bind it.",
      caption: "An illustrative yard. Not a project before-shot.",
    },
    {
      id: "00-atmosphere-prepare",
      kind: "intro",
      durationSeconds: 2,
      media: { src: "ai/prepare-atmosphere.mp4", kind: "video", ai: true },
      kicker: "SuperBase for hardstand",
      setup: "A third",
      payoff: "option.",
      body: "Between patching and a concrete slab.",
      caption: "The method, in five steps",
    },
    {
      id: "00-atmosphere-dose",
      kind: "intro",
      durationSeconds: 2,
      media: { src: "ai/dose-atmosphere.mp4", kind: "video", ai: true },
      kicker: "SuperBase for hardstand",
      setup: "A third",
      payoff: "option.",
      body: "Between patching and a concrete slab.",
      caption: "The method, in five steps",
      entranceOffsetFrames: 60,
    },
    {
      id: "00-atmosphere-roll",
      kind: "intro",
      durationSeconds: 2,
      media: { src: "ai/roll-atmosphere.mp4", kind: "video", ai: true },
      kicker: "SuperBase for hardstand",
      setup: "A third",
      payoff: "option.",
      body: "Between patching and a concrete slab.",
      caption: "The method, in five steps",
      entranceOffsetFrames: 120,
    },
    {
      id: "01-prepare-V01",
      kind: "process",
      durationSeconds: 4.5,
      media: {
        src: "footage/V01.mp4",
        kind: "video",
        startSeconds: 0,
        ai: false,
      },
      step: 1,
      kicker: "How it is built",
      setup: "Start with",
      payoff: "your base.",
      body: "Trimming the scarified base.",
      caption: "Recorded site footage · preparation",
    },
    {
      id: "02-dose-V02A",
      kind: "process",
      durationSeconds: 3.5,
      media: {
        src: "footage/V02A.mp4",
        kind: "video",
        startSeconds: 18.5,
        ai: false,
      },
      step: 2,
      kicker: "How it is built",
      setup: "Dose",
      payoff: "and mix.",
      body: "Water-cart dosing on the prepared base.",
      caption: "Recorded site footage · dosing",
    },
    {
      id: "03-grade-process-graphic",
      kind: "grade",
      durationSeconds: 4,
      step: 3,
      kicker: "How it is built",
      setup: "Grade",
      payoff: "to level.",
      body: "Trim to design level and crossfall.",
      caption: "Process illustration · not to scale",
    },
    {
      id: "04-roll-V03A",
      kind: "process",
      durationSeconds: 4.5,
      media: {
        src: "footage/V03A.mp4",
        kind: "video",
        startSeconds: 5,
        ai: false,
      },
      step: 4,
      kicker: "How it is built",
      setup: "Roll",
      payoff: "and compact.",
      body: "Compaction builds the bond.",
      caption: "Recorded site footage · rolling",
    },
    {
      id: "04-roll-V03B",
      kind: "process",
      durationSeconds: 3.5,
      media: {
        src: "footage/V03B.mp4",
        kind: "video",
        startSeconds: 5.5,
        ai: false,
      },
      step: 4,
      kicker: "How it is built",
      setup: "Roll",
      payoff: "and compact.",
      body: "Compaction builds the bond.",
      caption: "Recorded site footage · rolling",
      entranceOffsetFrames: 135,
    },
    {
      id: "05-cure-site-surface",
      kind: "surface",
      durationSeconds: 4,
      media: { src: "footage/S04B.jpeg", kind: "image", ai: false },
      step: 5,
      kicker: "How it is built",
      setup: "Allow",
      payoff: "to cure.",
      body: "Cure times vary by site.",
      caption: "Recorded site surface · timing unconfirmed",
    },
    {
      id: "proof-testing-process",
      kind: "proof",
      durationSeconds: 5,
      kicker: "Confirm on your material",
      setup: "Before.",
      payoff: "And after.",
      body: "Laboratory soaked CBR testing on your own yard material.",
      caption: "A testing method. No measured result is presented.",
    },
    {
      id: "indicative-cost",
      kind: "cost",
      durationSeconds: 5,
      kicker: "Indicative unit-rate comparison",
      setup: "60–70%",
      payoff: "Indicatively below\nengineered concrete\nhardstand.",
    },
    {
      id: "jon-contact-and-disclaimer",
      kind: "end",
      durationSeconds: 16,
      kicker: "A site trial is the next step",
      setup: "Let's look at",
      payoff: "your yard.",
      body: "Start with your material.\nConfirm with a site trial and testing.",
    },
  ],
});
